title: Lux Lavalier
description: Lux Lavalier is a beautiful wearable 40mm battery powered pendant necklace with 64 SK9822-2020 "HDR" RGB LEDs surface mounted in a Fibonacci distribution and a Pixelblaze V3 Pico controller built in.

# Build settings
plugins:
  - jekyll-feed

google_analytics: G-ZYKK881CJY

github_username: luxlavalier
instagram_username: jasoncoon
