theme: jekyll-theme-midnight
title: Lux Lavalier
description: Lux Lavalier is a beautiful 64mm circular disc with 64 RGB LEDs surface mounted in a Fibonacci distribution. Swirling and pulsing like a colorful galaxy, it's mesmerizing to watch.